# Generated by Django 5.2.15 on 2026-07-04 06:46

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gender', models.CharField(choices=[('MALE', 'Male'), ('FEMALE', 'Female')], max_length=10)),
                ('fitness_category', models.CharField(choices=[('BODYBUILDING', 'BodyBuilding'), ('POWERLIFTING', 'PowerLifting'), ('BOXING', 'Boxing'), ('WRESTLING', 'Wrestling'), ('CROSSFIT', 'Crossfit'), ('FITNESS', 'Fitness')], max_length=20)),
                ('fitness_goal', models.CharField(choices=[('WEIGHT_LOSS', 'WeightLoss'), ('MUSCLE_GAIN', 'MuscleGain'), ('STRENGTH', 'Strength'), ('ENDURANCE', 'Endurance')], max_length=20)),
                ('age', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(10), django.core.validators.MaxValueValidator(100)])),
                ('weight', models.FloatField(help_text='weight in kg', validators=[django.core.validators.MinValueValidator(30.0), django.core.validators.MaxValueValidator(250.0)])),
                ('height', models.FloatField(help_text='height in cm', validators=[django.core.validators.MinValueValidator(100.0), django.core.validators.MaxValueValidator(250.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
