# Generated by Django 5.2.15 on 2026-07-04 06:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='country',
            field=models.CharField(default='Georgia', help_text='country name', max_length=50, validators=[django.core.validators.RegexValidator(message='country name must be by alphabets', regex='^[a-zA-Z\\s]+$')]),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='phone_number',
            field=models.CharField(blank=True, help_text='phone number', max_length=17, validators=[django.core.validators.RegexValidator(message='phone number must be in this format: +995*********', regex='^\\+\\d{9,15}$')]),
        ),
    ]
