# Generated by Django 5.2.15 on 2026-07-05 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userprofile_is_vegetarian_userprofile_requires_hala'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='requires_hala',
            new_name='requires_halal',
        ),
    ]
