# Generated by Django 5.2.16 on 2026-07-07 17:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_requires_hala_userprofile_requires_halal'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='workout_location',
            field=models.CharField(choices=[('GYM', 'Gym (Full Equipment)'), ('HOME_BAND', 'Home with Resistance Bands'), ('BODYWEIGHT', 'Bodyweight Only (Calisthenics, Pull-ups, Push-ups)')], default='GYM', help_text='Where and with what equipment the user works out', max_length=20),
        ),
        migrations.CreateModel(
            name='AIPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_type', models.CharField(default='COMBINED', max_length=50)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fitness_plans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
