# Generated by Django 5.2.16 on 2026-07-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_workout_location_aiplan'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('water_intake_ml', models.IntegerField(default=0, help_text='Water intake in milliliters')),
                ('calories_consumed', models.IntegerField(default=0, help_text='Calories consumed today')),
                ('workout_completed', models.BooleanField(default=False, help_text="Did the user complete today's workout?")),
                ('notes', models.TextField(blank=True, help_text='Any optional notes from the user', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
