# Generated by Django 5.2.16 on 2026-07-11 20:42

import django.db.models.deletion
import users.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_dailylog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BodyAnalysisRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_front', models.ImageField(help_text='photo from front', upload_to=users.models.user_body_path)),
                ('image_back', models.ImageField(help_text='photo from behind', upload_to=users.models.user_body_path)),
                ('image_side_left', models.ImageField(help_text='photo from left side', upload_to=users.models.user_body_path)),
                ('image_side_right', models.ImageField(help_text='photo from right side', upload_to=users.models.user_body_path)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('ai_analysis_result', models.TextField(blank=True, null=True)),
                ('is_processed', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_analyses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
