# Generated by Django 5.2.16 on 2026-07-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_bodyanalysisrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiplan',
            name='has_visual_analysis',
            field=models.BooleanField(default=False, help_text='Does this plan made with photo analyze?'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='workout_days_per_week',
            field=models.IntegerField(choices=[(1, '1 days in week'), (2, '2 days in week'), (3, '3 days in week'), (4, '4 days in week'), (5, '5 days in week'), (6, '6 days in week'), (7, '7 days in week')], default=3, help_text='Days in week for workout'),
        ),
    ]
