# Generated by Django 5.2.16 on 2026-07-16 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_aiplan_has_visual_analysis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bodyanalysisrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='bodyanalysisrequest',
            name='ai_analysis_result',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
